version: "3"

networks:
  private:

volumes:
  pg_data:

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
    networks:
      - private
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: antuanuran/doc_comp:latest
    restart: always
    environment:
      - SECRET_KEY=dfgfeb43vbr7gbfcysdgbefyb4rcny4gbzxkexrasiweyd
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - private
    volumes:
      - ./static:/app/static
    depends_on:
      - db

       
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - private
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/static
    ports:
      - 80:80


    



